#include "../../catch.hpp"
#include <MorphologicalTree/MorphologicalTree.hpp>
#include <algorithm>


using namespace pomar;

SCENARIO("Morphological Tree initialize correctly") {
  GIVEN("An parent vector with 5 nodes generated by a set of vertices and by a order (increase)") {
    std::vector<unsigned char> vertices {
        2,0,3,
        2,1,3,
	7,0,3
    };

    std::vector<size_t> parent {
        4,1,4,
	0,1,2,
	0,1,2
    };
    
    std::vector<size_t> sortedIndex(vertices.size());
    std::iota(sortedIndex.begin(), sortedIndex.end(), 0);
    std::sort(sortedIndex.begin(), sortedIndex.end(), [&vertices](size_t i1, size_t i2) { return vertices[i1] < vertices[i2]; });

    WHEN("initialized a Morphological tree (max-tree)") {
      MorphologicalTree<unsigned char> tree(parent, sortedIndex, vertices);

      THEN("it should contains 5 nodes") {
	REQUIRE(tree.getNumberofNodes() == 5);
      }
      THEN("it should navigate the nodes in the following (level, number of CNPs)  order: (7,1), (3,3), (2,2), (1,1), (0,2)") {
	std::vector<size_t> levels {7,3,2,1,0};
	std::vector<size_t> nCNPs  {1,3,2,1,2}; 
	int i = 0;

	tree.transverseFromLeavesToRoot([&levels, &nCNPs, &i] (const MTNode<unsigned char>& node) {
	    levels[i] == node.level();
	    nCNPs[i++] == node.vertexIndexes().size();
	});
      }
    }
  }
}
